<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2019 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace Raylin666\Database\Database;

use Raylin666\Database\DB;
use Illuminate\Database\Eloquent\Model as EloquentModel;

/**
 * Class Model
 * @package Raylin666\Database\Database
 */
abstract class Model extends EloquentModel
{
    /**
     * @param null $name
     * @return \Illuminate\Database\Connection|mixed|null
     */
    public static function resolveConnection($name = null)
    {
        return DB::connection($name);
    }

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder|EloquentModel|Builder
     */
    public function newEloquentBuilder($query)
    {
        return new Builder($query); // TODO: Change the autogenerated stub
    }

    /**
     * @return Builder
     */
    public static function query()
    {
        return (new static)->newQuery();
    }

    /**
     * @return \Illuminate\Database\Connection|mixed|null
     */
    public function getConnection()
    {
        return static::resolveConnection($this->getConnectionName());
    }
}